import { SparklesIcon, LightBulbIcon } from "@heroicons/react/24/outline";
import type { GeneratedText } from "@/lib/api/types";

/**
 * AiBlock — ANY AI-generated content. Always visually distinct from verified
 * content: violet container, sparkles icon, an explicit AI label, and a
 * disclaimer (§0.2 — violet is load-bearing and reserved for this). Never
 * render generated text in a plain container.
 *
 * The "generated by AI, unverified" meaning is in the visible label AND the
 * block's accessible name, so it never depends on colour alone (§10).
 */
export function AiBlock({
  label,
  content,
  className = "",
}: {
  label: string; // e.g. "คำแปลโดย AI", "คำแนะนำโดย AI"
  content: GeneratedText;
  className?: string;
}) {
  const unverified = content.generation.review_status !== "approved";

  return (
    <section
      className={`rounded-control border border-violet-600/20 bg-violet-50 p-4 ${className}`}
      aria-label={`${label} — เนื้อหาสร้างโดย AI${
        unverified ? " ยังไม่ตรวจสอบ" : ""
      } (${content.generation.provider} · ${content.generation.model})`}
    >
      <header className="flex items-center gap-2 text-violet-600">
        <SparklesIcon className="h-[18px] w-[18px]" aria-hidden="true" />
        <span className="text-sm font-semibold">{label}</span>
        {unverified ? (
          <span className="rounded-chip bg-violet-600/10 px-2 py-0.5 text-xs font-medium text-violet-600">
            ยังไม่ตรวจสอบ
          </span>
        ) : null}
      </header>

      <div className="mt-2 text-[17px] leading-body text-ink-900">
        {content.text}
      </div>

      {content.disclaimer ? (
        <>
          <hr className="my-3 border-violet-600/15" />
          <p className="flex items-start gap-2 text-sm leading-body text-ink-600">
            <LightBulbIcon
              className="mt-0.5 h-4 w-4 shrink-0 text-amber-700"
              aria-hidden="true"
            />
            <span>{content.disclaimer}</span>
          </p>
        </>
      ) : null}

      {content.evidence?.length ? (
        <div className="mt-3 space-y-2">
          <p className="text-xs font-medium uppercase tracking-wide text-ink-400">
            หลักฐานจากเว็บ (ยังไม่ตรวจสอบ)
          </p>
          <ul className="space-y-2">
            {content.evidence.map((ev) => (
              <li
                key={ev.evidence_id}
                className="rounded-control border border-line bg-surface p-3 text-sm"
              >
                <p className="text-ink-900">“{ev.quote}”</p>
                <p className="mt-1 flex flex-wrap gap-x-2 text-ink-400">
                  <span>{ev.source}</span>
                  {ev.date ? <span>· {ev.date}</span> : null}
                  <a
                    href={ev.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-primary-600 underline"
                  >
                    ดูแหล่งที่มา
                  </a>
                </p>
              </li>
            ))}
          </ul>
        </div>
      ) : null}

      {/* provenance always visible, never colour-only (§10) */}
      <p className="mt-3 text-xs text-ink-400">
        สร้างโดย AI · {content.generation.provider} · {content.generation.model}
      </p>
    </section>
  );
}
